### ISSUE TITLE
Release date expectations

### ISSUE THREAD

**Issue by BenGroot** [tbruyelle/RxPermissions#11]
Due to the popularity of this amazing project I would like to know what the expected release date could be for a stable (production proof) version.

**Comment by BenGroot** [comment]
I'm sorry, I see that you're working on solutions to fix the rotation issue. I'll go through that thread to check the current status.

**Comment by tbruyelle** [comment]
Yes we need to fix #3 to have a stable release.

**Comment by BenGroot** [comment]
What if your app doesn't support screen rotation, are you confident to use it then?

**Comment by tbruyelle** [comment]
The screen rotation is only the visible part of the iceberg, we need to handle every configuration changes.
So no, locking the rotation change in your app is not enough.

However, since 0.2.0, there is no more crash, but the `onNext`'s code you registered before the configuration change will never be executed.

**Comment by BenGroot** [comment]
Clear, thanks! 
I can see that you're already looking at it with a lot of really smart people (including yourself). Although, I'll try to contribute if possible.

**Comment by tbruyelle** [comment]
Thanks for the compliment ^^ 
I hope we will find a proper solution.
