### ISSUE TITLE
Crashing with checkStateLoss below Android 6

### ISSUE THREAD

**Issue by ar-g** [tbruyelle/RxPermissions#114]
Why this lib creating fragment for Android versions below 6? I'm getting these crashes constantly. Version 0.9.1. 

```
java.lang.IllegalStateException
android.app.FragmentManagerImpl.checkStateLoss (FragmentManager.java:1318)
android.app.BackStackRecord.commit (BackStackRecord.java:586)
com.tbruyelle.rxpermissions.RxPermissions.getRxPermissionsFragment (RxPermissions.java:50)
com.tbruyelle.rxpermissions.RxPermissions. (RxPermissions.java)
classifieds.yalla.features.location.set_location.LocationOperations.checkLocationPermission (LocationOperations.java:232)```

**Comment by tbruyelle** [comment]
@epool Any idea ?

**Comment by epool** [comment]
@tbruyelle I'm not sure seems like the library it's being used in a activity and then the activity is finished quickly or something like that. @ar-g could you please tell us how are you using the library and/or share us a project to reproduce this issue please? In advance thanks.

**Comment by ar-g** [comment]
@epool I use the lib as in the example, strangely I get these crashes only below M. I don't think it's appropriate to add additional fragment if it's not used for the android version lower than M. I currently handle this manually, but I can send PR for the common fix. What do you think?

```java
public static Observable<Boolean> requestWriteExternalStoragePermission(Activity activity) {
    if (VERSION.SDK_INT >= VERSION_CODES.M) {
      return new RxPermissions(activity).request(Manifest.permission.WRITE_EXTERNAL_STORAGE);
    } else {
      boolean writeExternalStoragePermissionGranted =
          ContextCompat.checkSelfPermission(activity, Manifest.permission.WRITE_EXTERNAL_STORAGE)
              == PackageManager.PERMISSION_GRANTED;
      return Observable.just(writeExternalStoragePermissionGranted);
    }
  }
```

**Comment by epool** [comment]
@ar-g what is your current architecture or from where are you calling `requestWriteExternalStoragePermission(activity)`? Why are you doing a `new RxPermissions(activity)...` inside that method and not keep a `RxPermissions` instance on your class with the same scope of your activity?

**Comment by ar-g** [comment]
@epool This method gets called in the use-case method and triggers a long chain of operations; also use-case method can be triggered from different activity/fragment.

**Comment by ar-g** [comment]
@epool getting, even more, such crashes now. It is very weird creating new instances of `RxPermissions` shouldn't matter because, in the end, we are looking for the same fragment. 
```java
private RxPermissionsFragment findRxPermissionsFragment(Activity activity) {
        return (RxPermissionsFragment) activity.getFragmentManager().findFragmentByTag(TAG);
}
```
Also the other thing I noticed that it happens only on one screen.

**Comment by mrArtCore** [comment]
@ar-g 

Could you describe from what exactly 'view' you requested permissions ? Was it fragment, nested fragment or an activity ???  And could you give full error stacktrace? 
Because while you aint providing full stackTrace with java.lang.IllegalStateException "HERE WAS ERROR Message" I can only wondering what was got wrong.

But may be, just maybe If you requesting permissions from your fragment, you get crash that have described [on Stackowerflow](http://stackoverflow.com/questions/7575921/illegalstateexception-can-not-perform-this-action-after-onsaveinstancestate-wit)  or maybe you used  [wrong 'commit' method instead of commitAllowingStateLoss ](http://stackoverflow.com/questions/14860239/checking-if-state-is-saved-before-committing-a-fragmenttransaction)

If so, this is not library issue, this is yours, and you're allowed to fix it without any problems =)  

Also I tried to reproduce this crash with lib v0.9.1 on 4.4, 5.1 and 6.0 android devices and I couldn't...

**Comment by tbruyelle** [comment]
Closed because no response from op
