### ISSUE TITLE
I want to using dagger2 to inject RxPermission..

### ISSUE THREAD

**Issue by GitACDreamer** [tbruyelle/RxPermissions#116]
`@Provides
    @Singleton
    RxPermissions provideRxPermissions() {
       //how to pass an activity? and why not use context?
       //in the application class I can get the context ,but can not get the activity.
        return new RxPermissions(activity) 
    }`
In the previous version , I can using PxPermission.getInstance(). but now it removed ,it must has a activity parameter. In this case  how can I instantiate an  RxPermission object.

**Comment by tbruyelle** [comment]
Since we use a fragment to request the permission, `RxPermissions` now needs an activity.
It may be a constraint, but an activity is also needed if you request the permission with the core methods.

About your problem with Dagger, I suggest to create an other module in your activity, or to remove `RxPermissions` from injected dependencies, and create it manually.

**Comment by GitACDreamer** [comment]
thx,using 0.82 version `RxPermission.getInstance()` I solved this problem. because my project using MVP structure , I want coding request permission in the P Layer ,but activity/fragment.
