### ISSUE TITLE
Make RxPermissionsFragments extend support library Fragment

### ISSUE THREAD

**Issue by giovanniberti** [tbruyelle/RxPermissions#128]
To make the library compatible with the Android Support library, `RxPermissionFragment` could extend `android.support.v4.Fragment` instead of `android.app.Fragment`.
Is there anything major that prevents this?

**Comment by tbruyelle** [comment]
I dont think `RxPermissions` is currently not compatible with the Support lib.

**Comment by 3lements** [comment]
It is using `import android.app.FragmentManager` and `activity.getFragmentManager()`

**Comment by tbruyelle** [comment]
So is there good reason to use the support library ?

**Comment by agramian** [comment]
I have a use case for this. I need to use `FragmentManager.FragmentLifecycleCallbacks` to register callbacks for certain fragment events.  To use this on versions of Android below Oreo the `android.support.v4.app.FragmentManager` support version of the class must be used.  Since `RxPermissions` is not implemented using the support library versions of the `Fragment` and `FragmentManager` classes, I am unable to receive the callbacks for it.

**Comment by jeremyrempel** [comment]
android.app.Fragment was deprecated in API 28
