### ISSUE TITLE
A potential bug

### ISSUE THREAD

**Issue by boomstack** [tbruyelle/RxPermissions#146]
I see that this library uses fragment without user interface to process permissions, but it actually create a fragment, if the developer's activity has other fragments, they will run their own lifecycle, which is onResume, if developer process some logic in that method, it may cause problems.

**Comment by boomstack** [comment]
[PermissionBug.zip](https://github.com/tbruyelle/RxPermissions/files/991790/PermissionBug.zip)
this little project explains well. My devices run android 7.1.1

**Comment by epool** [comment]
@boomstack I'm not sure to figure out what case you are trying to consider as a potential bug. Since the fragments are totally independents between them there shouldn't be any problem between other fragments, each fragment just depends on the Activity lifecycle. I have seen your demo project but wasn't able to get your point, could you please explain your point better or even better update your demo project to show us the case you are considering  as a potential bug?

**Comment by epool** [comment]
@boomstack Feel free to reopen this issue if you consider it necessary.
