### ISSUE TITLE
Use Without Java8

### ISSUE THREAD

**Issue by isVoid** [tbruyelle/RxPermissions#151]
Google has deprecated Jack&Jill, support roadmap for Java8 is unclear. How to use RxPermission without lambda expressions?

**Comment by epool** [comment]
@isVoid actually this library doesn't require Java 8 to works, you could still using anonymous classes instead of lamdas, but if you really want to take advantage of the lamda syntax, you could use [Retrolambda](https://github.com/evant/gradle-retrolambda) or even still using Java 8 directly from Android Studio, google deprecated Jack toolchain but not Java 8 support, take a look [here](https://developer.android.com/studio/preview/features/java8-support.html).

**Comment by isVoid** [comment]
Thanks. Specifically, what anonymous class should I pass to .subscribe() function? I just switched from a legacy version, it seems like Action1 is no longer accessible in the new RxJava.

**Comment by isVoid** [comment]
Ah, as per [Rx API Docs](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0), Action1 has been renamed to Consumer. Thus it should be `.subscribe(new Consumer<Boolean>)`, the function to implement is `accept(Boolean)`

**Comment by epool** [comment]
also you could take a look at the sample project [here](https://github.com/tbruyelle/RxPermissions/blob/2.x/sample/src/main/java/com/tbruyelle/rxpermissions2/sample/MainActivity.java#L46)
