### ISSUE TITLE
What's the difference between Request and Ensure?

### ISSUE THREAD

**Issue by feinstein** [tbruyelle/RxPermissions#254]
I can't find any docs on the difference between `request` and `ensure`, the main sample uses them both without explanation, when should I use each of them?

**Comment by mrArtCore** [comment]
@feinstein If I'm not mistaken the difference is that `request` return `Observable` when `ensure` return `Observable.Transformer` so that you could use it  in `compose` function. See [compose]( http://reactivex.io/RxJava/javadoc/io/reactivex/Observable.html#compose-io.reactivex.ObservableTransformer- ) function javadoc for details.

**Comment by tbruyelle** [comment]
@mrArtCore correct explanation, thx.
