### ISSUE TITLE
onResume() invoke always

### ISSUE THREAD

**Issue by tinylpc** [tbruyelle/RxPermissions#98]
if the "new RxPermissions(this).request(permissions)" invoke in onResume() , the onReume() will cyclic call。
（the request permission is in refuse state）

**Comment by epool** [comment]
@tinylpc what is happening when you request some permission on the `onResume()` method is that android OS displays the permission dialog, then your activity is paused as you can see on [this diagram](https://developer.android.com/images/training/basics/basic-lifecycle-paused.png), and when you accept or reject the permission the permission dialog is closed and then your activity call the `onResume()` method again, and if you rejected the permission the permission is requested again because is on the `onResume()` method. Doesn't look like a bug, probably you should avoid requesting permissions on your `onResume()` method to avoid this behavior.

**Comment by tbruyelle** [comment]
Thx @epool. I'll fix the README.

**Comment by tinylpc** [comment]
thx @epool .
